swagger: '2.0'
info:
  title: amorphie.consent
  version: '1.0'
schemes: [https]
basePath: /OpenBankingConsentHHS
produces: [application/json]
consumes: [application/json]
security:
- auth: [retail-customer, openId]
securityDefinitions:
  auth:
    type: oauth2
    flow: password
    tokenUrl: https://test-pubagw6.burgan.com.tr/ebanking/token
    scopes: {retail-customer : retail-customer, openId : openId}
paths:
  /ProcessConsentStatus:
    post:
      description: Hesap Bilgisi Rızasının Hazırlanması
      summary: hesapBilgisiRizasi
      tags:
        - OpenBankingConsentHHS
      responses:
        '200':
          description: OK
      parameters:
      - {in: header, name: X-Request-ID, type: string, required: true, description: İsteği
          başlatan YÖS tarafından belirlenen çağrıya özgü talep kimliği, minLength: 1,
        maxLength: 36}
      - {in: header, name: X-Group-ID, type: string, required: true, description: İsteği
          başlatan YÖS tarafından belirlenen işlem akışına özgü talep kimliği, minLength: 1,
        maxLength: 36}
      - {in: header, name: PSU-Session-ID, type: string, required: false, description: İsteği
          başlatan YÖS tarafından belirlenen oturuma özgü talep kimliği, minLength: 1,
        maxLength: 100}
      - {in: header, name: X-ASPSP-Code, type: string, required: true, description: İsteğin
          iletildiği Hesap Hizmeti Sağlayıcısının kodudur, minLength: 4, maxLength: 4,
        pattern: '[0-9][0-9][0-9][0-9]'}
      - {in: header, name: X-TPP-Code, type: string, required: true, description: İsteği
          gönderen Yetkili Ödeme Hizmeti Sağlayıcısı (YÖS) kodudur, minLength: 4,
        maxLength: 4, pattern: '[0-9][0-9][0-9][0-9]'}
      - {in: header, name: PSU-Auth-Date, type: string, format: date-time, required: false,
        description: 'Müşterinin YÖS üzerinde en son oturum açtığı saat. [RFC7231]'}
      - {in: header, name: PSU-IP-Address, type: string, required: false, description: 'ÖHK
          YÖS üzerinde oturum açmışsa, işlemi başlattığı cihazın IP adresi.', minLength: 7,
        maxLength: 15}
      - {in: header, name: PSU-IP-Port, type: string, required: false, description: 'ÖHK
          YÖS üzerinde oturum açmışsa, işlemi başlattığı cihazın Port adresi.', minLength: 1,
        maxLength: 5}
      - {in: header, name: PSU-GEO-Location, type: string, required: false, description: 'ÖHK’nın
          işlemi başlattığı cihazın konum bilgisi. RFC2426 standartına uygun olarak
          paylaşılmalıdır. Örneğin GEO:"<enlem>,< boylam > GEO:52.506931,13.144558',
        minLength: 1, maxLength: 36}
      - name: body
        in: body
        schema: {$ref: '#/definitions/HesapBilgisiRizasiIstegiDTO'}
definitions:
  HesapBilgisiRizasiIstegiDTO:
    title: HesapBilgisiRizasiIstegi
    description: Hesap Bilgisi Rızası İsteği
    type: object
    example:
      katilimciBlg: {hhsKod: '8000', yosKod: '8000'}
      gkd: {yetYntm: Y, yonAdr: 'https://example.com'}
      kmlk: {kmlkTur: K, kmlkVrs: '77121323400', ohkTur: B}
      hspBlg:
        iznBlg:
          iznTur: ['01', '03']
          erisimIzniSonTrh: '2021-06-30T06:30:22+03:00'
host: nonprod-apisix.burgan.com.tr
