swagger: '2.0'
info:
  title: API PORTAL TEST
  version: '1.0'
schemes: [https]
#basePath: /OpenBankingConsentHHS
produces: [application/json]
consumes: [application/json]
security:
- auth: [retail-customer, openId]
securityDefinitions:
  auth:
    type: oauth2
    flow: password
    tokenUrl: https://nonprod-apisix.burgan.com.tr/ebanking/token
    scopes: {retail-customer : retail-customer, openId : openId}
paths:
  /OpenBankingConsentHHS/ProcessConsentStatus:
    post:
      description: Hesap Bilgisi Rızasının Hazırlanması
      summary: hesapBilgisiRizasi
      tags:
        - OpenBankingConsentHHS
      responses:
        '200':
          description: OK
      parameters:
      - {in: header, name: X-Request-ID, type: string, required: true, description: İsteği
          başlatan YÖS tarafından belirlenen çağrıya özgü talep kimliği, minLength: 1,
        maxLength: 36}
      - {in: header, name: X-Group-ID, type: string, required: true, description: İsteği
          başlatan YÖS tarafından belirlenen işlem akışına özgü talep kimliği, minLength: 1,
        maxLength: 36}
      - {in: header, name: PSU-Session-ID, type: string, required: false, description: İsteği
          başlatan YÖS tarafından belirlenen oturuma özgü talep kimliği, minLength: 1,
        maxLength: 100}
      - {in: header, name: X-ASPSP-Code, type: string, required: true, description: İsteğin
          iletildiği Hesap Hizmeti Sağlayıcısının kodudur, minLength: 4, maxLength: 4,
        pattern: '[0-9][0-9][0-9][0-9]'}
      - {in: header, name: X-TPP-Code, type: string, required: true, description: İsteği
          gönderen Yetkili Ödeme Hizmeti Sağlayıcısı (YÖS) kodudur, minLength: 4,
        maxLength: 4, pattern: '[0-9][0-9][0-9][0-9]'}
      - {in: header, name: PSU-Auth-Date, type: string, format: date-time, required: false,
        description: 'Müşterinin YÖS üzerinde en son oturum açtığı saat. [RFC7231]'}
      - {in: header, name: PSU-IP-Address, type: string, required: false, description: 'ÖHK
          YÖS üzerinde oturum açmışsa, işlemi başlattığı cihazın IP adresi.', minLength: 7,
        maxLength: 15}
      - {in: header, name: PSU-IP-Port, type: string, required: false, description: 'ÖHK
          YÖS üzerinde oturum açmışsa, işlemi başlattığı cihazın Port adresi.', minLength: 1,
        maxLength: 5}
      - {in: header, name: PSU-GEO-Location, type: string, required: false, description: 'ÖHK’nın
          işlemi başlattığı cihazın konum bilgisi. RFC2426 standartına uygun olarak
          paylaşılmalıdır. Örneğin GEO:"<enlem>,< boylam > GEO:52.506931,13.144558',
        minLength: 1, maxLength: 36}
      - name: body
        in: body
        schema: {$ref: '#/definitions/HesapBilgisiRizasiIstegiDTO'}
  
  /preprod-fora/DigitalServices/AccountService.svc/hesaplar/{accountNumber}:
   get:
     summary: Hesap bilgilerini getir
     tags:
        - Hesap Bilgileri
     parameters:
       - name: accountNumber
         in: path
         required: true
         type: string
         description: Hesap numarası
       - name: user
         in: header
         required: true
         type: string
         default: EBT\INTERNETUSER
       - name: CHANNEL
         in: header
         required: true
         type: string
         default: INTERNET
       - name: branch
         in: header
         required: true
         type: string
         default: 2000
       - name: Content-Type
         in: header
         required: true
         type: string
         default: application/json
       - name: izinTur
         in: header
         required: true
         type: string
         default: D
       - name: Cookie
         in: header
         required: false
         type: string
         default: ASP.NET_SessionId=...; d765907c0cd58c256b4df03b591a1a44=...
     responses:
       200:
         description: Başarılı cevap
         schema:
           type: object
           properties:
             data:
               type: object
               properties:
                 hesapBilgileri:
                   type: array
                   items:
                     type: object
                     properties:
                       hspDty:
                         type: object
                         properties:
                           hspAclsTrh:
                             type: string
                             format: date-time
                       hspTml:
                         type: object
                         properties:
                           hspDrm:
                             type: string
                           hspNo:
                             type: string
                           hspRef:
                             type: string
                           hspShb:
                             type: string
                           hspTip:
                             type: string
                           hspTur:
                             type: string
                           hspUrunAdi:
                             type: string
                           kisaAd:
                             type: string
                           prBrm:
                             type: string
                           subeAdi:
                             type: string
                       rizaNo:
                         type: string
                 toplamHesapSayisi:
                   type: integer
             error:
               type: object
       400:
         description: Geçersiz istek
       401:
         description: Yetkisiz
       500:
         description: Sunucu hatası
  /OpenBankingConsentHHS/GetCustomerBalancesByTckn/{tckn}:
   get:
     summary: TCKN ile müşteri bakiye bilgilerini getir
     tags:
        - Bakiye Bilgileri
     parameters:
       - name: tckn
         in: path
         required: true
         type: string
         description: Türkiye Cumhuriyeti Kimlik Numarası
       - name: accept
         in: header
         required: true
         type: string
         default: '*/*'
       - name: Authorization
         in: header
         required: true
         type: string
         description: Bearer token
         default: Bearer <token>
       - name: Cookie
         in: header
         required: false
         type: string
         default: d765907c0cd58c256b4df03b591a1a44=...
     responses:
       200:
         description: Başarılı cevap
         schema:
           type: object
           example:
             data:
               balances: []
             error: null
       400:
         description: Geçersiz istek
       401:
         description: Yetkisiz
       500:
         description: Sunucu hatası
definitions:
  HesapBilgisiRizasiIstegiDTO:
    title: HesapBilgisiRizasiIstegi
    description: Hesap Bilgisi Rızası İsteği
    type: object
    example:
      katilimciBlg: {hhsKod: '8000', yosKod: '8000'}
      gkd: {yetYntm: Y, yonAdr: 'https://example.com'}
      kmlk: {kmlkTur: K, kmlkVrs: '77121323400', ohkTur: B}
      hspBlg:
        iznBlg:
          iznTur: ['01', '03']
          erisimIzniSonTrh: '2021-06-30T06:30:22+03:00'
host: nonprod-apisix.burgan.com.tr
